### ISSUE TITLE
Handle missing ~/.kube/config gracefully

### ISSUE THREAD

**Issue by ankon** [Collaborne/load-kubeconfig#2]
~~~~

fs.js:584
 return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                ^

Error: ENOENT: no such file or directory, open '..../.kube/config'
   at Object.fs.openSync (fs.js:584:18)
   at Object.fs.readFileSync (fs.js:491:33)
   at Object.<anonymous> (...../node_modules/load-kubeconfig/index.js:12:31)
   at Module._compile (module.js:571:32)
   at Object.Module._extensions..js (module.js:580:10)
   at Module.load (module.js:488:32)
   at tryModuleLoad (module.js:447:12)
   at Function.Module._load (module.js:439:3)
   at Module.runMain (module.js:605:10)
   at run (bootstrap_node.js:427:7)
~~~~

**Comment by ankon** [comment]
Workaround could be to create the file empty:

```sh
mkdir .kube
cd .kube
echo "" > config
```
See also https://github.com/kubernetes/kubernetes/issues/34395
